name: UI Tests

on:
  workflow_run:
    workflows: ['Deploy Preview']
    types: [completed]

env:
  GIT_PAT: ${{ secrets.GIT_PAT }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  MNEMONIC_MAINNET: ${{ secrets.MNEMONIC_MAINNET }}
  MNEMONIC_METAMASK: ${{ secrets.MNEMONIC_METAMASK }}
  PATH_COSMOSTATION: './wallets/cosmostation'
  PATH_KEPLR: './wallets/keplr'
  PATH_LEAP: './wallets/leap'
  PATH_METAMASK: './wallets/metamask' 
  PRIVATE_KEY_METAMASK: ${{ secrets.PRIVATE_KEY_METAMASK }}
  PUBLIC_ADDRESS_CONTRACT_ETH: ${{ secrets.PUBLIC_ADDRESS_CONTRACT_ETH }}
  WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}

jobs:
  github-action-testnet:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone Playwright tests repository
        run: |
          git clone https://x-access-token:${{ secrets.GIT_PAT }}@github.com/neutron-org/neutron-end2end-tests.git --branch main --single-branch

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: ./neutron-end2end-tests
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./neutron-end2end-tests

      - name: Download Preview URLs Artifact
        uses: actions/download-artifact@v2
        with:
          name: preview-urls

      - name: Extract Testnet Preview URL
        id: extract-url
        run: |
          URL=$(grep -oP 'Preview URL: \K.*' netlify.txt | head -1)
          echo "Extracted Preview URL: $URL"
          echo "::set-output name=PREVIEW_URL::$URL"

      - name: Run Playwright tests for duality:ci
        run: yarn duality_testnet:ci
        working-directory: ./neutron-end2end-tests
        env:
          BASE_URL: ${{ steps.extract-url.outputs.PREVIEW_URL }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-ui
          path: ./neutron-end2end-tests/playwright-report/
          retention-days: 2

